title: kPherox Blog
description: >- # this means to ignore newlines until "baseurl:"
  My Notes

permalink: /:categories/:slug
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
